# Generated by Django 5.2.8 on 2025-11-21 14:15

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.TextField()),
                ('activity_date', models.DateTimeField()),
                ('activity_outcome', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField()),
                ('industry', models.TextField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('funding', models.BigIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('company_type', models.TextField(blank=True, null=True)),
                ('linkedin_company_url', models.TextField(blank=True, null=True)),
                ('search_url', models.TextField(blank=True, null=True)),
                ('headquarter', models.TextField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('establishment_date', models.TextField(blank=True, null=True)),
                ('company_summary', models.TextField(blank=True, null=True)),
                ('company_website', models.TextField(blank=True, null=True)),
                ('domain_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField(blank=True, null=True, unique=True)),
                ('job_title', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('email_status', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('search_document', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('seniority', models.TextField(blank=True, null=True)),
                ('sales_nav_url', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('connection_degree', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('sales_nav_profile_url', models.TextField(blank=True, null=True)),
                ('search_url', models.TextField(blank=True, null=True)),
                ('official_email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deal_name', models.TextField()),
                ('deal_stage', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('deal_owner', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'deals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('sequence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_name', models.TextField()),
                ('sequence_steps', models.JSONField()),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sequences',
                'managed': False,
            },
        ),
    ]
