# Generated by Django 3.2.25 on 2025-12-07 13:52

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField()),
                ('industry', models.TextField(blank=True, null=True)),
                ('headquarter', models.TextField(blank=True, null=True)),
                ('company_type', models.TextField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('establishment_date', models.DateField(blank=True, null=True)),
                ('company_summary', models.TextField(blank=True, null=True)),
                ('company_url', models.TextField(blank=True, null=True)),
                ('company_website', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('domain_name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('job_title', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('connection_degree', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
                ('sales_nav_profile_url', models.TextField(blank=True, null=True)),
                ('search_url', models.TextField(blank=True, null=True)),
                ('official_email', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('sequence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_name', models.TextField()),
                ('sequence_steps', djongo.models.fields.JSONField()),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sequences',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deal_name', models.TextField()),
                ('deal_stage', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('deal_owner', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.company')),
                ('contact', models.ForeignKey(db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.contact')),
            ],
            options={
                'db_table': 'deals',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.TextField()),
                ('activity_date', models.DateTimeField()),
                ('activity_outcome', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
